// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFK80JMKJkiJ2t8UAVscEFuk7_VVGFNK0',
    appId: '1:645991598326:web:7f4f38bd31d6ef421544d7',
    messagingSenderId: '645991598326',
    projectId: 'medicine-reminder-e07ef',
    authDomain: 'medicine-reminder-e07ef.firebaseapp.com',
    storageBucket: 'medicine-reminder-e07ef.firebasestorage.app',
    measurementId: 'G-Q8N8VMGXHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTOvdDOLuWoRHiTE6kxDMIy5HA7m3c-R0',
    appId: '1:645991598326:android:bffd2e9ac2b4b2d51544d7',
    messagingSenderId: '645991598326',
    projectId: 'medicine-reminder-e07ef',
    storageBucket: 'medicine-reminder-e07ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkrsBrUor6tvoYyybVxQJLRH8swZ9XXvM',
    appId: '1:645991598326:ios:4b2d9a80d43e97d81544d7',
    messagingSenderId: '645991598326',
    projectId: 'medicine-reminder-e07ef',
    storageBucket: 'medicine-reminder-e07ef.firebasestorage.app',
    iosBundleId: 'com.example.medicineReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkrsBrUor6tvoYyybVxQJLRH8swZ9XXvM',
    appId: '1:645991598326:ios:4b2d9a80d43e97d81544d7',
    messagingSenderId: '645991598326',
    projectId: 'medicine-reminder-e07ef',
    storageBucket: 'medicine-reminder-e07ef.firebasestorage.app',
    iosBundleId: 'com.example.medicineReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFK80JMKJkiJ2t8UAVscEFuk7_VVGFNK0',
    appId: '1:645991598326:web:58cf1baa90486c981544d7',
    messagingSenderId: '645991598326',
    projectId: 'medicine-reminder-e07ef',
    authDomain: 'medicine-reminder-e07ef.firebaseapp.com',
    storageBucket: 'medicine-reminder-e07ef.firebasestorage.app',
    measurementId: 'G-PNHD12TYWL',
  );
}
